[package]
name = "rust-mazes"
version = "0.1.0"
authors = ["Oleksandr Podze <dasdeg@gmail.com>"]
edition = "2018"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]


image = "0.22.5"
num-complex = "0.2.3"
rand = "0.7.2"
imageproc = "0.19.2"
gdk-pixbuf = "0.8.0"
cairo-rs = "0.8.0"
gio = "0.8.0"

[dependencies.gtk]
version = "0.8.0"
features = ["v3_16"]



